CREATE TABLE inquiries (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    inquiry_code    VARCHAR(40)  NOT NULL,
    user_id         BIGINT       NOT NULL,
    order_id        BIGINT,
    category        VARCHAR(30)  NOT NULL COMMENT 'ORDER/PRODUCT/PAYMENT/DELIVERY/RETURN/OTHER',
    title           VARCHAR(200) NOT NULL,
    content         TEXT         NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/ANSWERED/CLOSED',
    is_secret       BIT(1)       NOT NULL DEFAULT 0,
    answered_by_id  BIGINT,
    answered_at     DATETIME(6),
    answer_content  TEXT,
    created_at      DATETIME(6)  NOT NULL,
    updated_at      DATETIME(6)  NOT NULL,
    deleted_at      DATETIME(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_inquiries_code (inquiry_code),
    CONSTRAINT fk_inquiries_user    FOREIGN KEY (user_id)        REFERENCES users (id)   ON DELETE CASCADE,
    CONSTRAINT fk_inquiries_order   FOREIGN KEY (order_id)       REFERENCES orders (id)  ON DELETE SET NULL,
    CONSTRAINT fk_inquiries_admin   FOREIGN KEY (answered_by_id) REFERENCES admins (id)  ON DELETE SET NULL,
    INDEX idx_inquiries_user_id   (user_id),
    INDEX idx_inquiries_status    (status),
    INDEX idx_inquiries_created_at(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
